---
- name: Ensure required packages are installed
  apt:
    name: 
      - iputils-ping
      - curl 
      - ufw
      - net-tools
      - tcpdump
    state: present
    update_cache: true

# - name: Configure open ports with ufw (using the specified rules)
#   ufw:
#     rule: "{{ item.rule }}"
#     port: "{{ item.port }}"
#     proto: "{{ item.proto }}"
#   with_items: "{{ firewall_rules }}"

- name: Configure open ports with ufw (using the specified open ports)
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ open_ports }}"

- name: Configure default incoming/outgoing rules with ufw
  ufw:
    direction: "{{ item.direction }}"
    policy: "{{ item.policy }}"
  with_items: "{{ policies }}"

- name: activate ufw firewall
  ufw:
    state: enabled
